version: "3.7"

services:
  nginx:
    container_name: "dbapi"
    build: 
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - "8181:80"
    volumes:
      - app:/app
      - ./dbconfigs:/app/dbconfigs
  phpfpm:
    container_name: "phpfpm"
    build: 
      context: .
      dockerfile: ./Dockerfile.phpfpm
    volumes:
      - app:/app
  # redis:
  #   image: redis:alpine
    
volumes:
  app:
  