version: "3.7"
services:
  dbapi:
    restart: always
    image: "vsergione/dbapi:latest"
    environment:
      SECRET: myverysecuresecret
      CONFIGS_DIR: /var/www/dbconfigs
    ports:
      - "8989:80"
    volumes:
      - ../dbconfigs:/var/www/dbconfigs
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_USER: printopia
      MARIADB_PASSWORD: 1Pr1nt0p1@2!
      MARIADB_ROOT_PASSWORD: 1exemplu2!
      MARIADB_DATABASE: printopia
    volumes:
      - ./printopia.sql:/docker-entrypoint-initdb.d/printopia.sql
      - ./mysqldata:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8585:8080